### ISSUE TITLE
Audio Source not showing spotify on list

### ISSUE THREAD

**Issue by matallica81** [dsafa/audio-band#13] opened 2018-06-22 19:43 UTC
When I hover over the audio source option, no popout menu to select Spotify as audio source appears.

**Comment by matallica81** [comment] 2018-06-22 19:55
I just read through the other issue thread and see you're currently working on fixing this. Thank you for making this by the way!

**Comment by madcaddies420** [comment] 2018-06-23 16:20
Me aswell!  If needed, I can provide more information.

**Comment by Biiox** [comment] 2018-07-01 04:57
Duplicate of #3

**Closed** 2018-07-20 00:37 UTC

**Comment by dsafa** [comment] 2018-07-20 00:39
Thanks for reporting.
