### ISSUE TITLE
Audio Band not displaying any info

### ISSUE THREAD

**Issue by kushaal-nair** [dsafa/audio-band#111] opened 2019-03-11 16:58 UTC
Audio Band is not displaying any information while Spotify is playing music. No song info. 

**Checked common issues**
- Have uninstalled and reinstalled the toolbar
- Unchecked and checked the audio source

**Version Info**
 - Windows version 10
 - AudioBand Version  0.8.0

**Comment by dsafa** [comment] 2019-03-12 02:08
Attach the logs and I can take a look at it. `%temp%/AudioBand.log`

**Comment by kushaal-nair** [comment] 2019-03-18 16:44
[AudioBand.log](https://github.com/dsafa/audio-band/files/2979259/AudioBand.log)

**Comment by KazooieBreegull** [comment] 2019-03-19 21:03
was there ever a fix for this ? im having the same issue

**Comment by dsafa** [comment] 2019-03-21 17:17
Did you set up your spotify settings? (the client id and client secret. More info [here](https://dsafa.github.io/audio-band/audioband/audiosources/spotify.html))

**Comment by kushaal-nair** [comment] 2019-03-23 00:43
I've followed the steps and the controls appear to be working, although without displaying song info. Will test for a while and report if it does not change. Thank you @dsafa

**Comment by dsafa** [comment] 2019-03-25 05:33
Post the logs again if you do and I'll look at it again. There's been issues with spotify setup so it could just be that.

**Comment by kushaal-nair** [comment] 2019-03-28 07:05
Song title not displaying and play button does not work. Next and previous song buttons work. Attached log files as well. 
[AudioBand.log](https://github.com/dsafa/audio-band/files/3016575/AudioBand.log)

**Comment by dsafa** [comment] 2019-04-02 03:40
Can you post logs again? The ones you posted aren't complete (The logs get archived at the end of the day so its missing some information)

**Comment by kushaal-nair** [comment] 2019-04-02 17:02
[AudioBand.log](https://github.com/dsafa/audio-band/files/3035105/AudioBand.log)

**Comment by dsafa** [comment] 2019-04-06 00:00
I'm not seeing any errors or indication of an issue which is strange.
- When you press play/pause/next etc does it play/pause the song in spotify **but not** in audioband?

**Comment by kushaal-nair** [comment] 2019-04-11 18:11
As of now, none of the functionality works. The buttons do not produce any action on Spotify. I also do not know how to do a clean install, since certain files cannot be deleted

**Comment by dsafa** [comment] 2019-04-11 21:47
After running uninstall, you will need to restart explorer before deleting the files otherwise it will say the files are in use. There is also the settings file under the `AppData\Roaming\AudioBand` folder to delete.

Are you using the spotify desktop app? The playback buttons are essentially just emulating pressing the button in the app which is why those should at least work. I can't provide much help right now since I can't think of any root cause yet.

**Comment by kushaal-nair** [comment] 2019-04-12 16:36
I uninstalled and reinstalled. Re-did the Spotify app creation and now app works fine. Thank you.

**Comment by dsafa** [comment] 2019-04-12 18:27
Thats great! Too bad we never figured out the exact cause but I'm glad its working. I'll note it down for the future. Feel free to make another issue if the podcast switching issues become a big problem.

**Closed by dsafa** 2019-04-12 18:27 UTC
Labels: bug

**Comment by Tvdv013** [comment] 2020-05-23 10:10
I'm having this problem as well, nothing works or shows besides the next and previous buttons. Reinstalling Audioband And Spotify or making a new app didn't work.
